import type { Tool, ToolCategoryInfo } from "@/types";

/**
 * AEPERION — 39 HERRAMIENTAS INDIVIDUALES
 *
 * Cada herramienta puede adquirirse de forma separada.
 * Los planes incluyen una selección de estas herramientas.
 */

export const TOOL_CATEGORIES: ToolCategoryInfo[] = [
  {
    id: "web-presencia",
    name: "Presencia Web",
    icon: "globe",
    description: "Sitios web, landing pages y aplicaciones web profesionales",
  },
  {
    id: "automatizacion",
    name: "Automatización",
    icon: "bot",
    description: "Flujos automáticos de comunicación y procesos",
  },
  {
    id: "crm-ventas",
    name: "CRM y Ventas",
    icon: "users",
    description: "Gestión de clientes y pipelines de venta",
  },
  {
    id: "facturacion",
    name: "Facturación",
    icon: "file-text",
    description: "Facturación electrónica y gestión de ingresos",
  },
  {
    id: "pos-pagos",
    name: "POS y Pagos",
    icon: "credit-card",
    description: "Puntos de venta y procesamiento de pagos",
  },
  {
    id: "redes-sociales",
    name: "Redes Sociales",
    icon: "share2",
    description: "Gestión y crecimiento de presencia en redes",
  },
  {
    id: "administracion",
    name: "Administración",
    icon: "building",
    description: "Gestión interna de empleados, inventarios y agenda",
  },
  {
    id: "analitica",
    name: "Analítica y Datos",
    icon: "bar-chart",
    description: "Medición y visualización de datos del negocio",
  },
  {
    id: "comunicacion",
    name: "Comunicación",
    icon: "message-circle",
    description: "Canales de comunicación con clientes",
  },
  {
    id: "diseno",
    name: "Diseño y Marca",
    icon: "palette",
    description: "Identidad visual y materiales de marca",
  },
];

export const TOOLS: Tool[] = [
  // ===== PRESENCIA WEB (6) =====
  {
    id: "landing-page",
    name: "Landing Page Profesional",
    subtitle: "Página web de una página",
    description:
      "Página web profesional de una sola página ideal para negocios que inician su presencia digital.",
    longDescription:
      "Una landing page diseñada estratégicamente para captar clientes. Incluye secciones de hero, servicios, testimonios, contacto y más. Optimizada para conversión y carga rápida.",
    category: "web-presencia",
    price: 120000,
    icon: "layout-dashboard",
    hasDemo: true,
    demoType: "visual",
    features: [
      "Diseño responsive (mobile + desktop)",
      "Formulario de contacto",
      "Optimización SEO básica",
      "Integración WhatsApp",
      "Hosting incluido 1 año",
      "Dominio .com.co incluido",
    ],
    requirements: ["Contenido textual básico", "Logo en formato digital", "Fotos del negocio"],
    relatedTools: ["web-corporativa", "portafolio-pro", "analytics-web"],
    complexity: 1,
    popularity: 3,
  },
  {
    id: "web-corporativa",
    name: "Web Corporativa",
    subtitle: "Sitio web multi-página",
    description:
      "Sitio web profesional con múltiples páginas para empresas que necesitan presencia digital completa.",
    longDescription:
      "Sitio web corporativo con navegación completa, páginas interiores, blog integrado y panel administrativo básico. Ideal para empresas que quieren proyectar profesionalismo.",
    category: "web-presencia",
    price: 250000,
    icon: "building",
    hasDemo: true,
    demoType: "visual",
    features: [
      "Hasta 5 páginas",
      "Navegación profesional",
      "Blog integrado",
      "Formulario de contacto avanzado",
      "Galería de imágenes",
      "SEO completo",
      "Panel admin básico",
    ],
    requirements: ["Contenido de cada página", "Logo y brand assets", "Fotografías profesionales"],
    relatedTools: ["landing-page", "blog-integrado", "chat-en-vivo"],
    complexity: 2,
    popularity: 3,
  },
  {
    id: "ecommerce-basico",
    name: "E-commerce Básico",
    subtitle: "Tienda online",
    description:
      "Tienda online lista para vender productos con carrito de compras y pasarela de pagos.",
    longDescription:
      "Plataforma de comercio electrónico con catálogo de productos, carrito de compras, proceso de checkout y pasarela de pagos integrada. Ideal para negocios que quieren vender online.",
    category: "web-presencia",
    price: 350000,
    icon: "shopping-cart",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Catálogo de productos ilimitado",
      "Carrito de compras",
      "Pasarela de pagos",
      "Gestión de inventarios básico",
      "Notificaciones de pedidos",
      "Panel de administración",
    ],
    requirements: ["Catálogo de productos con fotos", "Cuenta bancaria o pasarela", "Logística de envíos"],
    relatedTools: ["pasarela-pagos", "factura-electronica", "inventarios"],
    complexity: 3,
    popularity: 2,
  },
  {
    id: "portafolio-pro",
    name: "Portafolio Profesional",
    subtitle: "Portafolio digital de proyectos",
    description:
      "Portafolio digital interactivo para profesionales que quieren mostrar su trabajo.",
    longDescription:
      "Portafolio profesional con galería de proyectos, filtros por categoría, modo presentación y enlace directo para compartir. Ideal para fotógrafos, diseñadores, arquitectos y creativos.",
    category: "web-presencia",
    price: 150000,
    icon: "image",
    hasDemo: true,
    demoType: "visual",
    features: [
      "Galería de proyectos",
      "Filtros por categoría",
      "Lightbox de imágenes",
      "Modo presentación",
      "Enlace personalizado",
      "Estadísticas de visitas",
    ],
    requirements: ["Imágenes de proyectos", "Descripciones de cada trabajo"],
    relatedTools: ["landing-page", "brand-kit", "analytics-web"],
    complexity: 1,
    popularity: 2,
  },
  {
    id: "blog-integrado",
    name: "Blog + CMS",
    subtitle: "Sistema de publicación de contenido",
    description:
      "Blog profesional con panel de administración para publicar contenido sin conocimientos técnicos.",
    longDescription:
      "Sistema de blog completo con editor visual, categorización, etiquetas, comentarios y SEO automático. Administra tu contenido desde un panel intuitivo.",
    category: "web-presencia",
    price: 180000,
    icon: "pen-tool",
    hasDemo: false,
    features: [
      "Editor visual (WYSIWYG)",
      "Categorías y etiquetas",
      "SEO automático",
      "Comentarios moderados",
      "Programación de publicaciones",
      "Panel administrativo",
    ],
    requirements: ["Contenido inicial (3+ artículos)", "Imágenes para artículos"],
    relatedTools: ["web-corporativa", "social-scheduler", "email-automation"],
    complexity: 2,
    popularity: 2,
  },
  {
    id: "web-app",
    name: "Web App a Medida",
    subtitle: "Aplicación web personalizada",
    description:
      "Aplicación web completamente personalizada para procesos de negocio específicos.",
    longDescription:
      "Desarrollo de aplicación web a medida con autenticación, base de datos, panel de administración y funcionalidades específicas para tu operación. Incluye 3 meses de soporte.",
    category: "web-presencia",
    price: 450000,
    icon: "code",
    hasDemo: false,
    features: [
      "Desarrollo a medida",
      "Autenticación de usuarios",
      "Base de datos",
      "Panel de administración",
      "API personalizada",
      "Soporte 3 meses",
    ],
    requirements: ["Brief detallado del proyecto", "Flujos de proceso documentados"],
    relatedTools: ["crm-avanzado", "dashboard-admin", "notificaciones"],
    complexity: 3,
    popularity: 2,
  },

  // ===== AUTOMATIZACIÓN (5) =====
  {
    id: "whatsapp-basico",
    name: "WhatsApp Básico",
    subtitle: "Auto-respuestas WhatsApp",
    description:
      "Sistema de respuestas automáticas para WhatsApp que atiende a tus clientes 24/7.",
    longDescription:
      "Configura mensajes automáticos de bienvenida, horarios de atención, respuestas rápidas y despedidas. Atiende a tus clientes incluso cuando no estás disponible.",
    category: "automatizacion",
    price: 90000,
    icon: "message-circle",
    hasDemo: true,
    demoType: "terminal",
    features: [
      "Mensaje de bienvenida automático",
      "Respuestas rápidas personalizadas",
      "Horarios de atención",
      "Mensaje de ausencia",
      "Estadísticas básicas",
    ],
    requirements: ["Número de WhatsApp Business", "Teléfono con WhatsApp Business instalado"],
    relatedTools: ["whatsapp-flow", "chatbot-simple", "chat-en-vivo"],
    complexity: 1,
    popularity: 3,
  },
  {
    id: "whatsapp-flow",
    name: "WhatsApp Flow",
    subtitle: "Flujo de clientes WhatsApp",
    description:
      "Automatización completa del flujo de atención al cliente por WhatsApp con menús interactivos.",
    longDescription:
      "Sistema de menús interactivos para WhatsApp que guía al cliente a través de opciones, captura información, deriva a áreas específicas y registra cada interacción en tu CRM.",
    category: "automatizacion",
    price: 180000,
    icon: "git-branch",
    hasDemo: true,
    demoType: "terminal",
    features: [
      "Menús interactivos",
      "Captura de datos del cliente",
      "Derivación a áreas",
      "Integración con CRM",
      "Historial de conversaciones",
      "Métricas de atención",
    ],
    requirements: ["WhatsApp Business activo", "Definición de flujos de atención"],
    relatedTools: ["whatsapp-basico", "crm-basico", "chatbot-simple"],
    complexity: 2,
    popularity: 3,
  },
  {
    id: "whatsapp-api",
    name: "WhatsApp API",
    subtitle: "API WhatsApp Business",
    description:
      "Integración avanzada con la API oficial de WhatsApp Business para automatización programática.",
    longDescription:
      "Conexión directa con la API oficial de WhatsApp Business Platform. Permite envío masivo, plantillas aprobadas, métricas avanzadas e integración con sistemas existentes.",
    category: "automatizacion",
    price: 280000,
    icon: "api",
    hasDemo: false,
    features: [
      "API oficial WhatsApp Business",
      "Plantillas de mensajes",
      "Envíos programados",
      "Notificaciones automáticas",
      "Métricas avanzadas",
      "Integración con sistemas existentes",
    ],
    requirements: ["Cuenta de Meta Business", "Número verificado en WhatsApp API"],
    relatedTools: ["whatsapp-flow", "crm-avanzado", "notificaciones"],
    complexity: 3,
    popularity: 2,
  },
  {
    id: "email-automation",
    name: "Email Marketing Automatizado",
    subtitle: "Campañas de correo automatizadas",
    description:
      "Sistema de email marketing con secuencias automatizadas, segmentación y analítica.",
    longDescription:
      "Plataforma de email marketing con constructor visual de campañas, segmentación de contactos, automatización de secuencias, pruebas A/B y reportes detallados.",
    category: "automatizacion",
    price: 120000,
    icon: "mail",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Editor de campañas visual",
      "Segmentación de contactos",
      "Secuencias automatizadas",
      "Pruebas A/B",
      "Reportes de apertura y clics",
      "Listas ilimitadas",
    ],
    requirements: ["Lista de contactos", "Correo corporativo"],
    relatedTools: ["landing-page", "crm-basico", "analytics-web"],
    complexity: 2,
    popularity: 2,
  },
  {
    id: "chatbot-simple",
    name: "Chatbot Web Inteligente",
    subtitle: "Asistente virtual para tu web",
    description:
      "Chatbot inteligente para tu sitio web que responde preguntas frecuentes y capta leads.",
    longDescription:
      "Asistente virtual basado en reglas que responde automáticamente las preguntas más frecuentes de tus clientes, captura información de contacto y deriva a un humano cuando es necesario.",
    category: "automatizacion",
    price: 200000,
    icon: "bot",
    hasDemo: true,
    demoType: "visual",
    features: [
      "Base de conocimiento personalizada",
      "Captura de leads",
      "Derivación a agente humano",
      "Personalización de apariencia",
      "Estadísticas de interacciones",
      "Disponible 24/7",
    ],
    requirements: ["FAQ documentada", "Horarios de atención humano"],
    relatedTools: ["whatsapp-flow", "chat-en-vivo", "crm-basico"],
    complexity: 2,
    popularity: 2,
  },

  // ===== CRM Y VENTAS (5) =====
  {
    id: "crm-basico",
    name: "CRM Esencial",
    subtitle: "Gestión de clientes simple",
    description:
      "Sistema CRM básico para organizar contactos, hacer seguimiento y cerrar más ventas.",
    longDescription:
      "CRM ligero pero potente con gestión de contactos, historial de interacciones, notas y recordatorios. Ideal para negocios que quieren dejar Excel y organizar sus clientes.",
    category: "crm-ventas",
    price: 200000,
    icon: "users",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Gestión de contactos",
      "Historial de interacciones",
      "Notas y recordatorios",
      "Etiquetas y segmentación",
      "Búsqueda avanzada",
      "Exportación de datos",
    ],
    requirements: ["Base de datos de clientes (importable)"],
    relatedTools: ["crm-avanzado", "funnel-ventas", "whatsapp-flow"],
    complexity: 1,
    popularity: 3,
  },
  {
    id: "crm-avanzado",
    name: "CRM Avanzado",
    subtitle: "CRM completo con reportes",
    description:
      "CRM profesional con pipeline de ventas, reportes, automatizaciones y dashboard ejecutivo.",
    longDescription:
      "Sistema CRM completo con gestión de oportunidades, pipeline visual, automatización de tareas, reportes personalizables, dashboard ejecutivo e integración con WhatsApp y email.",
    category: "crm-ventas",
    price: 350000,
    icon: "bar-chart-3",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Pipeline de ventas visual",
      "Automatización de tareas",
      "Reportes personalizables",
      "Dashboard ejecutivo",
      "Integración WhatsApp",
      "Integración email",
      "Múltiples usuarios",
    ],
    requirements: ["Procesos de venta definidos", "Equipo comercial"],
    relatedTools: ["crm-basico", "funnel-ventas", "kpi-dashboard"],
    complexity: 2,
    popularity: 3,
  },
  {
    id: "funnel-ventas",
    name: "Funnel de Ventas",
    subtitle: "Pipeline de ventas visual",
    description:
      "Sistema visual de seguimiento de oportunidades comerciales etapa por etapa.",
    longDescription:
      "Pipeline de ventas drag-and-drop con etapas personalizables, probabilidad de cierre, seguimiento automático y reportes de conversión.",
    category: "crm-ventas",
    price: 150000,
    icon: "funnel",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Pipeline visual drag & drop",
      "Etapas personalizables",
      "Probabilidad de cierre",
      "Seguimiento automático",
      "Reportes de conversión",
      "Notificaciones de actividad",
    ],
    requirements: ["Proceso de ventas definido"],
    relatedTools: ["crm-basico", "cotizador", "reportes-automaticos"],
    complexity: 1,
    popularity: 2,
  },
  {
    id: "cotizador",
    name: "Cotizador Automático",
    subtitle: "Cotizaciones en segundos",
    description:
      "Sistema que genera cotizaciones profesionales automáticamente según parámetros definidos.",
    longDescription:
      "Plataforma de cotización donde configuras productos/servicios con precios y variables, y el cliente recibe una cotización profesional instantánea. Ahorra horas de trabajo administrativo.",
    category: "crm-ventas",
    price: 120000,
    icon: "calculator",
    hasDemo: true,
    demoType: "form",
    features: [
      "Configuración de productos",
      "Precios variables",
      "Generación automática",
      "Formato PDF profesional",
      "Envío por email",
      "Historial de cotizaciones",
    ],
    requirements: ["Lista de productos con precios", "Reglas de negocio para cotización"],
    relatedTools: ["factura-electronica", "funnel-ventas", "invoice-pro"],
    complexity: 2,
    popularity: 3,
  },
  {
    id: "seguimiento-clientes",
    name: "Seguimiento Post-Venta",
    subtitle: "Automatización post-venta",
    description:
      "Sistema automatizado de seguimiento a clientes después de la compra para fidelización.",
    longDescription:
      "Automatización de comunicaciones post-venta: encuestas de satisfacción, recordatorios de renovación, ofertas personalizadas y reactivación de clientes inactivos.",
    category: "crm-ventas",
    price: 100000,
    icon: "repeat",
    hasDemo: false,
    features: [
      "Encuestas automáticas",
      "Recordatorios de renovación",
      "Ofertas personalizadas",
      "Reactivación de inactivos",
      "Métricas de retención",
      "Integración WhatsApp",
    ],
    requirements: ["Base de clientes con datos de contacto"],
    relatedTools: ["crm-basico", "email-automation", "whatsapp-flow"],
    complexity: 2,
    popularity: 2,
  },

  // ===== FACTURACIÓN (4) =====
  {
    id: "factura-electronica",
    name: "Facturación Electrónica",
    subtitle: "Facturación electrónica DIAN",
    description:
      "Sistema de facturación electrónica con cumplimiento de requisitos legales colombianos.",
    longDescription:
      "Plataforma de facturación electrónica que cumple con los requisitos de la DIAN. Genera facturas, notas crédito/débito, reportes y envía automáticamente al cliente y a la DIAN.",
    category: "facturacion",
    price: 200000,
    icon: "file-text",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Facturación electrónica DIAN",
      "Notas crédito y débito",
      "Envío automático al cliente",
      "Reportes fiscales",
      "Múltiples resoluciones",
      "Panel de facturación",
    ],
    requirements: ["NIT o RUT", "Resolución de facturación (si aplica)", "Firma electrónica"],
    relatedTools: ["invoice-pro", "presupuestos", "pos-basico"],
    complexity: 2,
    popularity: 3,
  },
  {
    id: "invoice-pro",
    name: "Facturación + Inventarios",
    subtitle: "Facturación avanzada con control de stock",
    description:
      "Sistema integrado de facturación y control de inventarios para gestión completa.",
    longDescription:
      "Solución que unifica facturación electrónica con control de inventarios en tiempo real. Cada factura descuenta automáticamente del stock, alerta cuando hay mínimo y genera órdenes de compra.",
    category: "facturacion",
    price: 300000,
    icon: "archive",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Facturación + inventarios integrados",
      "Control de stock en tiempo real",
      "Alertas de stock mínimo",
      "Órdenes de compra",
      "Proveedores",
      "Reportes de rotación",
    ],
    requirements: ["Inventario inicial", "Productos con códigos"],
    relatedTools: ["factura-electronica", "inventarios", "pos-avanzado"],
    complexity: 2,
    popularity: 2,
  },
  {
    id: "presupuestos",
    name: "Presupuestos Automáticos",
    subtitle: "Presupuestos profesionales instantáneos",
    description:
      "Sistema que genera presupuestos profesionales con plantillas personalizables.",
    longDescription:
      "Herramienta de presupuestación con plantillas profesionales, cálculo automático de impuestos y descuentos, conversión a factura con un clic y envío directo al cliente.",
    category: "facturacion",
    price: 100000,
    icon: "file-text",
    hasDemo: true,
    demoType: "form",
    features: [
      "Plantillas personalizables",
      "Cálculo automático de IVA",
      "Descuentos por volumen",
      "Conversión a factura",
      "Envío por email/WhatsApp",
      "Aprobación digital",
    ],
    requirements: ["Lista de productos/servicios con precios"],
    relatedTools: ["cotizador", "factura-electronica", "funnel-ventas"],
    complexity: 1,
    popularity: 2,
  },
  {
    id: "contabilidad-basica",
    name: "Libro Contable Digital",
    subtitle: "Contabilidad digital simplificada",
    description:
      "Sistema básico de contabilidad digital para llevar registros ordenados y reportes simples.",
    longDescription:
      "Libro contable digital con registro de ingresos y egresos, categorización, generación de P&L básico, exportación a Excel y preparación para contador.",
    category: "facturacion",
    price: 150000,
    icon: "book-open",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Registro de ingresos y egresos",
      "Categorización automática",
      "Estado P&L básico",
      "Exportación a Excel",
      "Preparación para contador",
      "Reportes mensuales",
    ],
    requirements: ["Historial de transacciones"],
    relatedTools: ["factura-electronica", "invoice-pro", "reportes-automaticos"],
    complexity: 2,
    popularity: 1,
  },

  // ===== POS Y PAGOS (4) =====
  {
    id: "pos-basico",
    name: "POS Básico",
    subtitle: "Punto de venta esencial",
    description:
      "Sistema de punto de venta básico para facturar y cobrar de forma rápida.",
    longDescription:
      "Punto de venta intuitivo con catálogo de productos, cobro rápido, múltiples métodos de pago, cierre de caja diario y reportes básicos de ventas.",
    category: "pos-pagos",
    price: 250000,
    icon: "credit-card",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Catálogo de productos",
      "Cobro rápido",
      "Múltiples métodos de pago",
      "Cierre de caja diario",
      "Reportes de ventas",
      "Impresión de tickets",
    ],
    requirements: ["Lista de productos con precios", "Impresora térmica (opcional)"],
    relatedTools: ["pos-avanzado", "factura-pos", "inventarios"],
    complexity: 1,
    popularity: 3,
  },
  {
    id: "pos-avanzado",
    name: "POS Avanzado",
    subtitle: "POS completo con inventarios y reportes",
    description:
      "Punto de venta profesional con gestión de inventarios, múltiples cajas y analytics.",
    longDescription:
      "Sistema POS completo con gestión de inventarios en tiempo real, múltiples puntos de venta, control de cajeros, promociones, descuentos y dashboard de ventas en vivo.",
    category: "pos-pagos",
    price: 400000,
    icon: "monitor",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Múltiples puntos de venta",
      "Inventarios en tiempo real",
      "Control de cajeros",
      "Promociones y descuentos",
      "Dashboard de ventas en vivo",
      "Reportes comparativos",
    ],
    requirements: ["Infraestructura de red básica", "Equipos POS"],
    relatedTools: ["pos-basico", "factura-pos", "crm-avanzado"],
    complexity: 2,
    popularity: 2,
  },
  {
    id: "pasarela-pagos",
    name: "Pasarela de Pagos",
    subtitle: "Pagos online integrados",
    description:
      "Integración de pagos online para recibir pagos con tarjeta, transferencia y más.",
    longDescription:
      "Conexión con pasarelas de pago colombianas (Wompi, PayU, Epayco) para recibir pagos online de forma segura. Incluye checkout personalizado, notificaciones y conciliación.",
    category: "pos-pagos",
    price: 180000,
    icon: "banknote",
    hasDemo: false,
    features: [
      "Checkout personalizado",
      "Múltiples medios de pago",
      "Pago recurrente (suscripciones)",
      "Notificaciones de pago",
      "Conciliación automática",
      "Panel de transacciones",
    ],
    requirements: ["Cuenta en pasarela de pagos", "Cuenta bancaria empresarial"],
    relatedTools: ["ecommerce-basico", "factura-electronica", "pos-basico"],
    complexity: 2,
    popularity: 3,
  },
  {
    id: "factura-pos",
    name: "POS + Facturación Unificado",
    subtitle: "POS y facturación en un solo sistema",
    description:
      "Sistema que unifica punto de venta con facturación electrónica para una operación sin fricción.",
    longDescription:
      "La solución más completa para comercios: POS integrado con facturación electrónica DIAN. Cada venta genera automáticamente la factura legal, descuenta del inventario y actualiza contabilidad.",
    category: "pos-pagos",
    price: 350000,
    icon: "combine",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "POS + Facturación integrados",
      "Factura electrónica automática",
      "Inventario sincronizado",
      "Múltiples formas de pago",
      "Cierre fiscal diario",
      "Reportes integrados",
    ],
    requirements: ["Resolución DIAN", "Equipo POS", "Conexión a internet estable"],
    relatedTools: ["pos-avanzado", "factura-electronica", "invoice-pro"],
    complexity: 3,
    popularity: 3,
  },

  // ===== REDES SOCIALES (4) =====
  {
    id: "social-scheduler",
    name: "Programación de Contenido",
    subtitle: "Publicaciones programadas en redes",
    description:
      "Programa y gestiona el contenido de tus redes sociales desde un solo panel.",
    longDescription:
      "Calendario editorial visual para programar publicaciones en Instagram, Facebook, LinkedIn y TikTok. Incluye sugerencias de mejores horarios, vistas previa y analytics.",
    category: "redes-sociales",
    price: 80000,
    icon: "calendar",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Calendario editorial visual",
      "Publicación automática",
      "Sugerencia de horarios",
      "Vista previa de posts",
      "Analítica básica",
      "Multi-cuenta",
    ],
    requirements: ["Cuentas de redes sociales empresariales"],
    relatedTools: ["social-analytics", "content-creator", "social-crm"],
    complexity: 1,
    popularity: 2,
  },
  {
    id: "social-analytics",
    name: "Analítica de Redes",
    subtitle: "Métricas y reportes de redes sociales",
    description:
      "Panel de analítica avanzada para medir el rendimiento de tus redes sociales.",
    longDescription:
      "Dashboard con métricas clave de todas tus redes sociales: alcance, engagement, crecimiento, mejores contenidos y recomendaciones accionables.",
    category: "redes-sociales",
    price: 120000,
    icon: "bar-chart-4",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Métricas multi-red",
      "Reportes de alcance",
      "Análisis de engagement",
      "Crecimiento por período",
      "Top contenidos",
      "Exportación de reportes",
    ],
    requirements: ["Cuentas de redes vinculadas", "Mínimo 1 mes de datos"],
    relatedTools: ["social-scheduler", "kpi-dashboard", "reportes-automaticos"],
    complexity: 1,
    popularity: 2,
  },
  {
    id: "content-creator",
    name: "Generación de Contenido Visual",
    subtitle: "Diseño de contenido para redes",
    description:
      "Crea contenido visual profesional para redes sociales con plantillas inteligentes.",
    longDescription:
      "Herramienta de diseño de contenido visual con plantillas profesionales adaptadas a cada red social. Genera imágenes, carruseles, stories y videos cortos optimizados.",
    category: "redes-sociales",
    price: 150000,
    icon: "palette",
    hasDemo: true,
    demoType: "visual",
    features: [
      "Plantillas por red social",
      "Editor visual drag & drop",
      "Biblioteca de recursos",
      "Generación de carruseles",
      "Dimensiones automáticas",
      "Exportación en lote",
    ],
    requirements: ["Brand assets (logo, colores, fuentes)"],
    relatedTools: ["brand-kit", "social-scheduler", "identidad-corporativa"],
    complexity: 2,
    popularity: 2,
  },
  {
    id: "social-crm",
    name: "Social CRM",
    subtitle: "Gestión de clientes desde redes",
    description:
      "Centraliza los mensajes y leads de todas tus redes sociales en un solo lugar.",
    longDescription:
      "Unifica los mensajes, comentarios y leads de Instagram, Facebook, LinkedIn y WhatsApp en un solo panel. Responde desde un solo lugar y registra cada interacción.",
    category: "redes-sociales",
    price: 180000,
    icon: "message-square",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Bandeja unificada multi-red",
      "Respuesta centralizada",
      "Etiquetado de leads",
      "Historial de interacciones",
      "Asignación a vendedores",
      "Métricas de respuesta",
    ],
    requirements: ["Cuentas de redes vinculadas"],
    relatedTools: ["crm-basico", "whatsapp-flow", "social-analytics"],
    complexity: 2,
    popularity: 2,
  },

  // ===== ADMINISTRACIÓN (4) =====
  {
    id: "hr-basico",
    name: "Gestión de Empleados",
    subtitle: "Administración de personal básica",
    description:
      "Sistema de gestión de empleados con control de asistencia, vacaciones y datos.",
    longDescription:
      "Panel de administración de personal con registro de empleados, control de asistencia, solicitudes de vacaciones, documentos y reportes básicos de nómina.",
    category: "administracion",
    price: 150000,
    icon: "briefcase",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Registro de empleados",
      "Control de asistencia",
      "Solicitudes de vacaciones",
      "Documentos digitales",
      "Reportes de nómina básicos",
      "Roles y permisos",
    ],
    requirements: ["Lista de empleados con datos básicos"],
    relatedTools: ["dashboard-admin", "agenda-digital", "notificaciones"],
    complexity: 2,
    popularity: 2,
  },
  {
    id: "inventarios",
    name: "Control de Inventarios",
    subtitle: "Gestión de stock y productos",
    description:
      "Sistema de control de inventarios con alertas, órdenes y reportes de rotación.",
    longDescription:
      "Gestión completa de inventarios con múltiples almacenes, control de lotes, alertas de stock mínimo, órdenes de compra automáticas y reportes de rotación.",
    category: "administracion",
    price: 200000,
    icon: "package",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Múltiples almacenes",
      "Control de lotes",
      "Alertas de stock mínimo",
      "Órdenes de compra",
      "Reportes de rotación",
      "Códigos de barras",
    ],
    requirements: ["Inventario inicial con cantidades", "Códigos de producto"],
    relatedTools: ["pos-avanzado", "invoice-pro", "factura-pos"],
    complexity: 2,
    popularity: 2,
  },
  {
    id: "agenda-digital",
    name: "Agenda / Calendario Compartido",
    subtitle: "Agenda digital del equipo",
    description:
      "Calendario compartido para coordinar citas, reuniones y tareas del equipo.",
    longDescription:
      "Agenda digital colaborativa con calendario compartido, agendamiento de citas con clientes, recordatorios automáticos, disponibilidad en tiempo real y sincronización multi-dispositivo.",
    category: "administracion",
    price: 80000,
    icon: "calendar-check",
    hasDemo: true,
    demoType: "visual",
    features: [
      "Calendario compartido",
      "Agendamiento de citas",
      "Recordatorios automáticos",
      "Disponibilidad en tiempo real",
      "Sincronización multi-dispositivo",
      "Notificaciones SMS/WhatsApp",
    ],
    requirements: ["Ninguno (listo para usar)"],
    relatedTools: ["hr-basico", "whatsapp-basico", "notificaciones"],
    complexity: 1,
    popularity: 3,
  },
  {
    id: "dashboard-admin",
    name: "Panel Administrativo",
    subtitle: "Dashboard de gestión empresarial",
    description:
      "Panel centralizado para administrar todas las áreas de tu negocio.",
    longDescription:
      "Dashboard administrativo que centraliza la información de todas tus herramientas: ventas, clientes, inventarios, facturación y empleados en un solo lugar con gráficos y alertas.",
    category: "administracion",
    price: 250000,
    icon: "layout-dashboard",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Vista general del negocio",
      "Gráficos de ventas",
      "Alertas inteligentes",
      "Acceso rápido a herramientas",
      "Reportes ejecutivos",
      "Personalización de widgets",
    ],
    requirements: ["Mínimo 2 herramientas activas de Aeperion"],
    relatedTools: ["kpi-dashboard", "crm-avanzado", "reportes-automaticos"],
    complexity: 2,
    popularity: 2,
  },

  // ===== ANALÍTICA (3) =====
  {
    id: "analytics-web",
    name: "Analítica Web",
    subtitle: "Métricas de tu sitio web",
    description:
      "Panel de analítica web con métricas de tráfico, comportamiento y conversiones.",
    longDescription:
      "Analítica web first-party (sin dependencia de terceros) con métricas de visitas, páginas vistas, tiempo en sitio, tasa de rebote, embudos de conversión y mapa de calor.",
    category: "analitica",
    price: 100000,
    icon: "area-chart",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "Métricas de tráfico",
      "Comportamiento de usuarios",
      "Embudos de conversión",
      "Mapa de calor (heatmap)",
      "Reportes automáticos",
      "Sin cookies de terceros",
    ],
    requirements: ["Sitio web activo con código de tracking"],
    relatedTools: ["landing-page", "web-corporativa", "kpi-dashboard"],
    complexity: 1,
    popularity: 3,
  },
  {
    id: "reportes-automaticos",
    name: "Reportes Automatizados",
    subtitle: "Reportes programados a tu correo",
    description:
      "Generación y envío automático de reportes periódicos del rendimiento de tu negocio.",
    longDescription:
      "Sistema de reportes automáticos que recopila datos de todas tus herramientas y envía reportes periódicos (diarios, semanales, mensuales) a los correos que definas.",
    category: "analitica",
    price: 120000,
    icon: "file-bar-chart",
    hasDemo: false,
    features: [
      "Reportes programados",
      "Multi-frecuencia (diario/semanal/mensual)",
      "PDF y Excel",
      "Múltiples destinatarios",
      "Métricas personalizables",
      "Comparativas por período",
    ],
    requirements: ["Al menos una herramienta Aeperion activa"],
    relatedTools: ["kpi-dashboard", "analytics-web", "dashboard-admin"],
    complexity: 1,
    popularity: 2,
  },
  {
    id: "kpi-dashboard",
    name: "Dashboard de KPIs",
    subtitle: "Tablero de indicadores clave",
    description:
      "Dashboard visual con los indicadores clave de rendimiento de tu negocio en tiempo real.",
    longDescription:
      "Tablero de KPIs personalizable con indicadores en tiempo real, metas, alertas cuando algo requiere atención, y visualizaciones claras para tomar decisiones informadas.",
    category: "analitica",
    price: 200000,
    icon: "gauge",
    hasDemo: true,
    demoType: "dashboard",
    features: [
      "KPIs personalizables",
      "Metas y alertas",
      "Datos en tiempo real",
      "Visualizaciones claras",
      "Exportación ejecutiva",
      "Vista mobile",
    ],
    requirements: ["Fuentes de datos definidas", "Objetivos de negocio claros"],
    relatedTools: ["dashboard-admin", "reportes-automaticos", "analytics-web"],
    complexity: 2,
    popularity: 2,
  },

  // ===== COMUNICACIÓN (2) =====
  {
    id: "chat-en-vivo",
    name: "Chat en Vivo para Web",
    subtitle: "Atención en vivo en tu sitio",
    description:
      "Sistema de chat en vivo para atender clientes en tiempo real desde tu sitio web.",
    longDescription:
      "Widget de chat en vivo con notificaciones en tiempo real, historial de conversaciones, asignación a agentes, respuestas rápidas y métricas de atención.",
    category: "comunicacion",
    price: 80000,
    icon: "message-circle",
    hasDemo: true,
    demoType: "visual",
    features: [
      "Widget de chat personalizable",
      "Notificaciones en tiempo real",
      "Historial de conversaciones",
      "Asignación a agentes",
      "Respuestas rápidas",
      "Métricas de atención",
    ],
    requirements: ["Sitio web activo", "Horarios de atención"],
    relatedTools: ["chatbot-simple", "whatsapp-flow", "social-crm"],
    complexity: 1,
    popularity: 2,
  },
  {
    id: "notificaciones",
    name: "Sistema de Notificaciones",
    subtitle: "Alertas inteligentes multi-canal",
    description:
      "Sistema centralizado de notificaciones por email, WhatsApp y SMS.",
    longDescription:
      "Motor de notificaciones que envía alertas automáticas por múltiples canales (email, WhatsApp, SMS) basado en eventos de tu negocio: ventas, alertas de stock, recordatorios, etc.",
    category: "comunicacion",
    price: 100000,
    icon: "bell",
    hasDemo: false,
    features: [
      "Multi-canal (email/WhatsApp/SMS)",
      "Notificaciones basadas en eventos",
      "Plantillas personalizables",
      "Programación de envíos",
      "Historial de notificaciones",
      "Métricas de entrega",
    ],
    requirements: ["Conexión a servicios de mensajería"],
    relatedTools: ["email-automation", "whatsapp-api", "agenda-digital"],
    complexity: 2,
    popularity: 2,
  },

  // ===== DISEÑO Y MARCA (2) =====
  {
    id: "brand-kit",
    name: "Kit de Marca Digital",
    subtitle: "Elementos básicos de marca",
    description:
      "Paquete digital con los elementos esenciales de identidad de marca para tu negocio.",
    longDescription:
      "Kit digital de marca que incluye logo en múltiples formatos, paleta de colores con códigos, tipografías seleccionadas, papelería básica digital y guía de uso rápida.",
    category: "diseno",
    price: 120000,
    icon: "image",
    hasDemo: false,
    features: [
      "Logo en múltiples formatos",
      "Paleta de colores con códigos",
      "Tipografías seleccionadas",
      "Papelería digital básica",
      "Guía de uso rápida",
      "Archivos editables",
    ],
    requirements: ["Referencias de estilo", "Brief de marca"],
    relatedTools: ["identidad-corporativa", "content-creator", "landing-page"],
    complexity: 1,
    popularity: 2,
  },
  {
    id: "identidad-corporativa",
    name: "Identidad Visual Completa",
    subtitle: "Sistema de identidad de marca completo",
    description:
      "Sistema completo de identidad visual corporativa con manual de marca y todos los activos.",
    longDescription:
      "Desarrollo completo de identidad visual: logo principal y variantes, paleta de color extendida, tipografía corporativa, iconografía, papelería completa, señalética digital, plantillas para redes y presentaciones, y manual de marca.",
    category: "diseno",
    price: 250000,
    icon: "brush",
    hasDemo: false,
    features: [
      "Logo principal + variantes",
      "Paleta extendida",
      "Tipografía corporativa",
      "Iconografía personalizada",
      "Papelería completa",
      "Manual de marca digital",
      "Plantillas para redes",
      "Plantillas para presentaciones",
    ],
    requirements: ["Brief de marca detallado", "Referencias visuales"],
    relatedTools: ["brand-kit", "content-creator", "landing-page"],
    complexity: 3,
    popularity: 2,
  },
];
